language: php

php:
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer self-update --no-interaction

script:
    - php vendor/bin/phpstan.phar analyse --level 7 src/

jobs:
    include:
        - stage: Code Quality
          env: DB=none STATIC_ANALYSIS
          install: composer update --prefer-dist
          script: vendor/bin/phpstan analyse --level 7 src/
